rules:
  - id: wrong-handling-priority-queue
    patterns:
      - pattern: |
          void produci_alta_prio(PriorityProdCons* $P){
              ...
              while( ... ) {
              ...
              }
          ...
          }
      - pattern-not-inside: |
          ...
          $P->$THREADS++;
          ...
          $P->$THREADS--;
          ...
      - pattern-not-inside: |
          ...
          $P->$THREADS = $P->$THREADS + 1;
          ...
          $P->$THREADS = $P->$THREADS - 1;
          ...

    message: In questo esercizio, è necessario che i produttori incrementino una variabile di conteggio
             subito prima di chiamare cond_wait(), e che la decrementino subito dopo la chiamata a cond_wait().
             Queste variabili di conteggio consentono di sapere se ci sono thread ad alta priorità in attesa,
             e di dargli la precedenza quando il consumatore deve risvegliare dei produttori.
    languages:
      - c
    severity: ERROR

  - id: missing-while-cicle
    patterns:
      - pattern-either:
          - patterns:
              - pattern: |
                  void consuma(...){
                    ...
                  }
              - pattern-not-inside: ... while(...){...}
          - patterns:
              - pattern: |
                  void produci_bassa_prio(...){
                    ...
                  }
              - pattern-not-inside: ... while(...){...}
          - patterns:
              - pattern: |
                  void produci_alta_prio(...){
                    ...
                  }
              - pattern-not-inside: ... while(...){...}

    message: La condizione va controllata all'interno di un ciclo "while".
             Nei programmi basati su libreria PThreads, il monitor è sempre di tipo signal-and-continue.
    languages:
      - c
    severity: ERROR

  - id: wake-producers-inorder-up
    patterns:
      - pattern: |
         void consuma(...){
           ...
         }
      - pattern-not-inside: |
         ...
         if($TH1 > 0){
           ...
           pthread_cond_signal(...);
           ...
         } else {
           ...
           pthread_cond_signal(...);
           ...
         }
         ...
      - pattern-not-inside: |
         ...
         if($TH1 > 0){
           ...
           pthread_cond_signal(...);
           ...
         } else if($TH2 > 0){
           ...
           pthread_cond_signal(...);
           ...
         }
         ...
      - pattern-not-inside: |
         ...
         if($TH1 > 0)
           pthread_cond_signal(...);
         else if($TH2 > 0)
           pthread_cond_signal(...);
         ...
      - pattern-not-inside: |
         ...
         if($TH1 > 0)
           pthread_cond_signal(...);
         else
           pthread_cond_signal(...);
         ...

    message: È necessario controllare che il consumatore verifichi la presenza di produttori ad alta priorità in attesa e risvegliare loro.
             Altrimenti, il consumatore risveglia un produttore a bassa priorità.
    languages:
      - c
    severity: ERROR

